name: 'OpenSCAD HiRes renderer'
description: 'Creates hi-res images from OpenSCAD script'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  camera:
    description: 'OpenSCAD camera position'
    required: false
    default: ''

  picture:
    description: 'Target picture name (with extension)'
    required: false
    default: ''

  projection:
    description: '''ortho'' or ''perspective'''
    required: false
    default: 'perspective'

  render:
    description: 'full OpenSCAD geometry evaluation when exporting png'
    required: false
    default: false

  resolution:
    description: 'Target resolution in ''openscad'' format i.e. 800x600'
    required: false
    default:  '800x600'

  script:
    description: 'OpenSCAD script'
    required: true

runs:
  using: 'docker'
  image: 'docker://ggabbiani/git-actions:fedora'
  args:
    - --resolution
    - ${{ inputs.resolution }}
    - --camera
    - ${{ inputs.camera }}
    - --projection
    - ${{ inputs.projection }}
    - --image
    - ${{ inputs.picture }}
    - ${{ inputs.script }}
    - ${{ inputs.render == 'true' && '--render' }}
