# This is a basic workflow to help you get started with Actions

name: Docker build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the trunk branch
  push:
    branches: [ trunk ]
    tags: [ "v*.*.*" ]

  pull_request:
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  base-image:
    name: Static pre-requisites
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: base
      DOCKER_IMAGE: "${{ vars.DOCKERHUB_USERNAME }}/renderer-base:v1.0.0"

    steps:

      # Checks-out repo on $GITHUB_WORKSPACE
      - name: Project checkout
        uses: actions/checkout@v6
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
          fetch-depth: '0'

      # Check if anything in docker/base/* changed with the last commit.
      - name: Docker base changes
        id: base
        run: |
          set +e
          (git diff --name-only HEAD HEAD~1 | grep -e '^docker/base/' >/dev/null && echo yes || echo no) | xargs -I@ echo changed=@ >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Docker Hub Login
        if: steps.base.outputs.changed == 'yes'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Base build and push
        if: steps.base.outputs.changed == 'yes'
        run: |
          make docker/.base BASE_IMG="${{ env.DOCKER_IMAGE }}"

  docker-image:
    name: Renderer Docker image
    needs: [base-image]
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: git-actions:fedora
      DOCKER_IMAGE: "${{ vars.DOCKERHUB_USERNAME }}/renderer:v1.0.0"

    steps:

      # Checks-out repo on $GITHUB_WORKSPACE
      - name: Project checkout
        uses: actions/checkout@v6
        with:
          # Number of commits to fetch. 0 indicates all history for all branches
          # and tags (default 1).
          fetch-depth: '0'

      # Check if anything in docker/fedora/* or /bin/* changed with the last commit.
      # See also
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      # and
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
      - name: Docker changes
        id: docker
        run: |
          set +e
          (git diff --name-only HEAD HEAD~1 | grep -e '^docker/renderer/' -e '^bin/' >/dev/null && echo yes || echo no) | xargs -I@ echo changed=@ >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Docker Hub Login
        if: steps.docker.outputs.changed == 'yes'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push via Makefile
        if: steps.docker.outputs.changed == 'yes'
        run: |
          make RENDERER_IMG=${{ env.DOCKER_IMAGE }}

  tests:
    name: Regression tests
    needs: [docker-image]
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Default inputs test
        uses: ./ # repo path where to find action.yaml
        with:
          script:     'tests/logo.scad'         # root relative path to OpenSCAD script

      - name: Overriden inputs test
        uses: ./
        with:
          script:   'tests/logo.scad'
          picture:  'tests/overriden-logo.png'  # picture name override
          render:   true                        # render flag override
          camera:   '0,0,0,55,0,25,140'

      - name: Verifica e Archiviazione
        if: success()
        uses: actions/upload-artifact@v7
        with:
          path: tests/*logo.png

  parameter-sets:
    name: Parameter sets
    needs: [docker-image]
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Parameter set 1
        uses: ./
        with:
          script:   'tests/cust-parms.scad'
          picture:  'tests/pset-1.png'  # picture name override

      - name: Parameter set 2
        uses: ./
        with:
          script:   'tests/cust-parms.scad'
          picture:  'tests/pset-2.png'  # picture name override

      - name: Verifica e Archiviazione
        if: success()
        uses: actions/upload-artifact@v7
        with:
          path: tests/pset-*.png

      # - name: Commit and Push changes
      #   if: github.ref_type == 'branch'
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "docs: update test results [skip ci]"
      #     file_pattern: 'tests/pset-*.png'

  call-release:
    name: Draft release
    needs: [tests,parameter-sets]
    # Questa è la condizione chiave: gira solo se l'evento corrente è un TAG
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/draft-release.yaml # Punta al file di release