name: Live Test OpenSCAD
on:
  push:
    branches: [ trunk ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v6

      - name: Using defaults
        uses: ./ # repo path where to find action.yaml
        with:
          resolution: '800x600'
          script:     'tests/logo.scad' # root relative path to OpenSCAD script
          picture:    'tests/logo.png'  # root relative path to the produced image
          projection: 'ortho'

      - name: Overriden inputs
        uses: ./
        with:
          resolution: '1024x768'
          script:     'tests/logo.scad'
          picture:    'tests/logo.png'
          projection: 'ortho'
