name: Regression tests
on:
  workflow_run:
    workflows: ["Docker Build"]
    types: [completed]
  push:
    branches: [ trunk ]
  workflow_dispatch:      # <--- explicit run

# a new triggered test (i.e. from a 'workflow_run'),
# cancel the eventually running previous one (i.e. the one triggered from a 'push').
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v6

      - name: Using defaults
        uses: ./ # repo path where to find action.yaml
        with:
          script:     'tests/logo.scad'         # root relative path to OpenSCAD script

      - name: Overriden inputs
        uses: ./
        with:
          script:     'tests/logo.scad'
          picture:    'tests/overriden-logo.png'  # picture name override
          render: true                            # render flag override
          camera: '0,0,0,55,0,25,140'

      - name: Verifica e Archiviazione
        if: success()
        uses: actions/upload-artifact@v7
        with:
          path: tests/*.png

